#pragma once
#include <lvgl.h>

// Single source of truth for the pre-baked bitmap font inventory. Each entry
// has a matching font_<face>_<size>.c (generated by lv_font_conv — see the
// README "Regenerating fonts" section) compiled into the build. Adding or
// removing a size means: (1) generate/delete the .c file, (2) update the
// README regen loop, (3) add/remove the declaration here. There is no runtime
// rasterizer (FreeType/TinyTTF are disabled).
LV_FONT_DECLARE(font_tiempos_56);
LV_FONT_DECLARE(font_tiempos_34);
LV_FONT_DECLARE(font_styrene_48);
LV_FONT_DECLARE(font_styrene_36);
LV_FONT_DECLARE(font_styrene_28);
LV_FONT_DECLARE(font_styrene_24);
LV_FONT_DECLARE(font_styrene_20);
LV_FONT_DECLARE(font_styrene_16);
LV_FONT_DECLARE(font_mono_32);
