#!/usr/bin/env python3
"""Generate firmware/src/splash_animations.h from manifest.json + .bin files.

Reads tools/svg_anim_data/manifest.json and the per-animation *.bin files,
then writes the C header that firmware/src/splash.cpp includes.

Importable API
--------------
  needs_regen(in_dir, out_file) -> bool
      True if out_file is missing OR any manifest.json / *.bin in in_dir has
      a newer mtime than out_file.

  generate(in_dir, out_file) -> None
      Read manifest + bins, emit the header.

CLI
---
  python3 gen_splash_header.py [--in DIR] [--out FILE]
  Defaults: --in  <repo>/tools/svg_anim_data
            --out <repo>/firmware/src/splash_animations.h

Only stdlib (json, re, os, sys, argparse) — no Pillow/numpy — so this
runs inside PlatformIO's bundled Python during the firmware build.
"""

import argparse
import json
import os
import re
import sys

# ---------------------------------------------------------------------------
# Repo-relative defaults (resolve from this file's location)
# ---------------------------------------------------------------------------
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
# _SCRIPT_DIR is tools/svg_pipeline/; repo root is two levels up
_REPO_ROOT = os.path.dirname(os.path.dirname(_SCRIPT_DIR))
_DEFAULT_IN = os.path.join(_REPO_ROOT, "tools", "svg_anim_data")
_DEFAULT_OUT = os.path.join(_REPO_ROOT, "firmware", "src", "splash_animations.h")

PALETTE_SIZE = 24

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _safe_ident(s):
    """Mirror the JS safeIdent: lower-case, non-alphanumeric runs → '_',
    strip leading/trailing underscores."""
    result = re.sub(r"[^a-z0-9]+", "_", s.lower())
    return result.strip("_")


def _hex_to_rgb565(hex_color):
    """Convert '#rrggbb' (or 'transparent'/None/empty) to uint16 RGB565."""
    if not hex_color or hex_color == "transparent":
        return 0x0000
    h = hex_color.lstrip("#")
    if len(h) == 3:
        h = h[0] * 2 + h[1] * 2 + h[2] * 2
    r = int(h[0:2], 16)
    g = int(h[2:4], 16)
    b = int(h[4:6], 16)
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def _palette_to_rgb565(palette_hex, size=None):
    """Return list of `size` uint16 values; missing entries pad with 0."""
    if size is None:
        size = PALETTE_SIZE
    out = [0x0000] * size
    for i, h in enumerate(palette_hex):
        if i >= size:
            break
        out[i] = _hex_to_rgb565(h)
    return out


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def needs_regen(in_dir, out_file):
    """Return True if the header is absent or older than any source file."""
    if not os.path.exists(out_file):
        return True
    out_mtime = os.path.getmtime(out_file)
    manifest = os.path.join(in_dir, "manifest.json")
    if not os.path.exists(manifest):
        return True
    # Generator script itself: editing emit logic should trigger a rebuild.
    if os.path.getmtime(__file__) > out_mtime:
        return True
    if os.path.getmtime(manifest) > out_mtime:
        return True
    for fname in os.listdir(in_dir):
        if fname.endswith(".bin") and os.path.getmtime(os.path.join(in_dir, fname)) > out_mtime:
            return True
    return False


def generate(in_dir, out_file):
    """Read manifest.json + *.bin files in in_dir; write C header to out_file."""
    manifest_path = os.path.join(in_dir, "manifest.json")
    if not os.path.exists(manifest_path):
        sys.exit(f"ERROR: manifest not found at {manifest_path}. Run frames_to_data.py first.")

    with open(manifest_path, encoding="utf-8") as f:
        manifest = json.load(f)

    palette_size = manifest.get("palette_size", PALETTE_SIZE)
    animations = manifest["animations"]

    out = []
    out.append("// ============================================================\n")
    out.append("// Splash animations — generated by tools/svg_pipeline/gen_splash_header.py.\n")
    out.append("// Source: clawd-tank SVG animations (MIT, marciogranzotto/clawd-tank),\n")
    out.append("// rasterized headless at the per-anim width x height and palette-reduced.\n")
    out.append("// Do not edit by hand — re-run the converter to refresh.\n")
    out.append("// ============================================================\n")
    out.append(f"// Each animation carries a {palette_size}-entry RGB565 palette.\n")
    out.append(f"// Cell values 0..{palette_size - 1} index into palette.\n")
    out.append("// Animations are per-anim width x height (current set: 128x128).\n")
    out.append("// frames[] is an array of pointers to width*height-byte index grids\n")
    out.append("// so sizes can be mixed.\n")
    out.append('// group: usage-rate tier name ("idle"/"normal"/"active"/"heavy") —\n')
    out.append("// propagated from animations.json; splash.cpp maps it to a rate-group\n")
    out.append("// index via RATE_TIERS for rate-driven animation selection.\n")
    out.append("#pragma once\n#include <stdint.h>\n\n")

    out.append(f"#define SPLASH_PALETTE_SIZE {palette_size}\n\n")

    out.append("typedef struct {\n")
    out.append("    const char *name;\n")
    out.append("    const char *group;\n")
    out.append("    uint8_t width;\n")
    out.append("    uint8_t height;\n")
    out.append("    uint16_t frame_count;\n")
    out.append("    const uint16_t *palette;\n")
    out.append("    const uint8_t * const *frames;\n")
    out.append("    const uint16_t *holds;\n")
    out.append("} splash_anim_def_t;\n\n")

    entries = []

    for anim in animations:
        # ident: strip .bin suffix, apply safeIdent
        bin_stem = anim["bin"].replace(".bin", "")  # e.g. "clawd_idle_living"
        ident = _safe_ident(bin_stem)

        name = anim["name"]
        if "group" not in anim:
            sys.exit(
                f"ERROR: manifest entry '{anim.get('bin', name)}' is missing 'group' — "
                "regenerate manifest.json with frames_to_data.py"
            )
        group = anim["group"]
        W = anim["width"]
        H = anim["height"]
        frame_count = anim["frame_count"]
        holds = anim["holds"]
        palette_hex = anim["palette"]

        # palette
        pal565 = _palette_to_rgb565(palette_hex, palette_size)
        pal_str = ",".join(f"0x{v:04X}" for v in pal565)
        out.append(
            f"static const uint16_t splash_{ident}_palette[{palette_size}] = {{{pal_str}}};\n"
        )

        # read binary pixel data
        bin_path = os.path.join(in_dir, anim["bin"])
        with open(bin_path, "rb") as bf:
            raw = bf.read()
        expected = frame_count * H * W
        if len(raw) != expected:
            sys.exit(f"ERROR: {anim['bin']} is {len(raw)} bytes, expected {expected}")

        # one flat array per frame
        for fi in range(frame_count):
            offset = fi * H * W
            frame_bytes = raw[offset : offset + H * W]
            pixels_str = ",".join(str(b) for b in frame_bytes)
            out.append(f"static const uint8_t splash_{ident}_f{fi}[{W * H}] = {{{pixels_str}}};\n")

        # pointer table
        ptr_str = ",".join(f"splash_{ident}_f{fi}" for fi in range(frame_count))
        out.append(
            f"static const uint8_t * const splash_{ident}_frames[{frame_count}] = {{{ptr_str}}};\n"
        )

        # holds
        holds_str = ",".join(str(h) for h in holds)
        out.append(
            f"static const uint16_t splash_{ident}_holds[{frame_count}] = {{{holds_str}}};\n\n"
        )

        entries.append(
            {
                "ident": ident,
                "name": name,
                "group": group,
                "width": W,
                "height": H,
                "count": frame_count,
            }
        )

    out.append(f"#define SPLASH_ANIM_COUNT {len(entries)}\n")
    out.append("static const splash_anim_def_t splash_anims[SPLASH_ANIM_COUNT] = {\n")
    for e in entries:
        out.append(
            f'    {{"{e["name"]}", "{e["group"]}", {e["width"]}, {e["height"]}, '
            f"{e['count']}, splash_{e['ident']}_palette, splash_{e['ident']}_frames, "
            f"splash_{e['ident']}_holds}},\n"
        )
    out.append("};\n")

    content = "".join(out)
    os.makedirs(os.path.dirname(os.path.abspath(out_file)), exist_ok=True)
    with open(out_file, "w", encoding="utf-8") as f:
        f.write(content)
    size_kb = len(content) / 1024
    print(f"Wrote {out_file} ({len(entries)} animations, {size_kb:.1f} KB)")


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(
        description="Generate splash_animations.h from manifest.json + .bin files."
    )
    parser.add_argument(
        "--in", dest="in_dir", default=_DEFAULT_IN, help=f"Input directory (default: {_DEFAULT_IN})"
    )
    parser.add_argument(
        "--out",
        dest="out_file",
        default=_DEFAULT_OUT,
        help=f"Output header (default: {_DEFAULT_OUT})",
    )
    args = parser.parse_args()
    generate(args.in_dir, args.out_file)


if __name__ == "__main__":
    main()
